"""initial schema

Revision ID: fb431915efe4
Revises: 
Create Date: 2026-09-17 11:02:45.272555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb431915efe4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(length=128), nullable=False),
    sa.Column('scheme', sa.String(length=64), nullable=False),
    sa.Column('pivot', sa.String(length=16), nullable=False),
    sa.Column('judge', sa.String(length=128), nullable=False),
    sa.Column('backtranslator_panel', sa.JSON(), nullable=False),
    sa.Column('method_version', sa.String(length=32), nullable=False),
    sa.Column('hardware_profile', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_tags', sa.JSON(), nullable=False),
    sa.Column('unknown_tags', sa.JSON(), nullable=False),
    sa.Column('max_calls', sa.Integer(), nullable=True),
    sa.Column('calls_used', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_engine'), 'job', ['engine'], unique=False)
    op.create_index(op.f('ix_job_method_version'), 'job', ['method_version'], unique=False)
    op.create_index(op.f('ix_job_status'), 'job', ['status'], unique=False)
    op.create_table('qualification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtranslator', sa.String(length=128), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('method_version', sa.String(length=32), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backtranslator', 'tag', 'method_version', name='uq_qualification_identity')
    )
    op.create_index(op.f('ix_qualification_backtranslator'), 'qualification', ['backtranslator'], unique=False)
    op.create_index(op.f('ix_qualification_tag'), 'qualification', ['tag'], unique=False)
    op.create_table('generation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('engine', sa.String(length=128), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('spec_id', sa.String(length=64), nullable=True),
    sa.Column('designator', sa.String(length=256), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('usage', sa.JSON(), nullable=True),
    sa.Column('latency_s', sa.Float(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_engine'), 'generation', ['engine'], unique=False)
    op.create_index(op.f('ix_generation_job_id'), 'generation', ['job_id'], unique=False)
    op.create_index(op.f('ix_generation_kind'), 'generation', ['kind'], unique=False)
    op.create_index(op.f('ix_generation_tag'), 'generation', ['tag'], unique=False)
    op.create_table('job_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('cls', sa.String(length=64), nullable=False),
    sa.Column('representative', sa.String(length=64), nullable=False),
    sa.Column('members', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'cls', name='uq_job_item_class')
    )
    op.create_index(op.f('ix_job_item_job_id'), 'job_item', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_item_status'), 'job_item', ['status'], unique=False)
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('engine', sa.String(length=128), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('cls', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('evidence', sa.String(length=32), nullable=False),
    sa.Column('s_lang', sa.Float(), nullable=False),
    sa.Column('s_content', sa.Float(), nullable=False),
    sa.Column('ci_low', sa.Float(), nullable=False),
    sa.Column('ci_high', sa.Float(), nullable=False),
    sa.Column('borderline', sa.Boolean(), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('refusals', sa.Integer(), nullable=False),
    sa.Column('designator', sa.String(length=256), nullable=False),
    sa.Column('designator_detail', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('variant_evidence', sa.String(length=32), nullable=True),
    sa.Column('inherited_from', sa.String(length=64), nullable=True),
    sa.Column('resolves_to', sa.JSON(), nullable=True),
    sa.Column('backtranslator', sa.String(length=128), nullable=False),
    sa.Column('backtranslator_qualification', sa.JSON(), nullable=False),
    sa.Column('judge', sa.String(length=128), nullable=False),
    sa.Column('pivot', sa.String(length=16), nullable=False),
    sa.Column('hardware_profile', sa.String(length=32), nullable=True),
    sa.Column('method_version', sa.String(length=32), nullable=False),
    sa.Column('tool_version', sa.String(length=32), nullable=True),
    sa.Column('rungs_run', sa.Integer(), nullable=True),
    sa.Column('calls', sa.JSON(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engine', 'tag', 'method_version', 'backtranslator', name='uq_result_identity')
    )
    op.create_index(op.f('ix_result_cls'), 'result', ['cls'], unique=False)
    op.create_index(op.f('ix_result_engine'), 'result', ['engine'], unique=False)
    op.create_index('ix_result_engine_tier', 'result', ['engine', 'tier'], unique=False)
    op.create_index(op.f('ix_result_evidence'), 'result', ['evidence'], unique=False)
    op.create_index(op.f('ix_result_job_id'), 'result', ['job_id'], unique=False)
    op.create_index(op.f('ix_result_method_version'), 'result', ['method_version'], unique=False)
    op.create_index(op.f('ix_result_tag'), 'result', ['tag'], unique=False)
    op.create_index(op.f('ix_result_tested_at'), 'result', ['tested_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_result_tested_at'), table_name='result')
    op.drop_index(op.f('ix_result_tag'), table_name='result')
    op.drop_index(op.f('ix_result_method_version'), table_name='result')
    op.drop_index(op.f('ix_result_job_id'), table_name='result')
    op.drop_index(op.f('ix_result_evidence'), table_name='result')
    op.drop_index('ix_result_engine_tier', table_name='result')
    op.drop_index(op.f('ix_result_engine'), table_name='result')
    op.drop_index(op.f('ix_result_cls'), table_name='result')
    op.drop_table('result')
    op.drop_index(op.f('ix_job_item_status'), table_name='job_item')
    op.drop_index(op.f('ix_job_item_job_id'), table_name='job_item')
    op.drop_table('job_item')
    op.drop_index(op.f('ix_generation_tag'), table_name='generation')
    op.drop_index(op.f('ix_generation_kind'), table_name='generation')
    op.drop_index(op.f('ix_generation_job_id'), table_name='generation')
    op.drop_index(op.f('ix_generation_engine'), table_name='generation')
    op.drop_table('generation')
    op.drop_index(op.f('ix_qualification_tag'), table_name='qualification')
    op.drop_index(op.f('ix_qualification_backtranslator'), table_name='qualification')
    op.drop_table('qualification')
    op.drop_index(op.f('ix_job_status'), table_name='job')
    op.drop_index(op.f('ix_job_method_version'), table_name='job')
    op.drop_index(op.f('ix_job_engine'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
